management:
  security:
    enabled: false

      
info:
  app:
    name: @project.name@
    description: @project.description@
  
      
      
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss             